[package]
name = "colorfs"
version = "0.1.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
image = "0.14.0"
libc = "0.2.24"
time = "0.1.37"

[dependencies.fuse_mt]
git = "https://github.com/sector-f/fuse-mt.git"
rev = "d2a4101"
